[package]
org = "ballerina"
name = "crypto"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["security", "hash", "hmac", "sign", "encrypt", "decrypt", "private key", "public key"]
repository = "https://github.com/ballerina-platform/module-ballerina-crypto"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "crypto-native"
version = "@toml.version@"
path = "../native/build/libs/crypto-native-@project.version@.jar"

[[platform.java17.dependency]]
path = "./lib/bcpkix-jdk15to18-@bouncycastle.version@.jar"

[[platform.java17.dependency]]
path = "./lib/bcprov-jdk15to18-@bouncycastle.version@.jar"
