[package]
org = "ballerina"
name = "crypto"
version = "2.2.2"
authors = ["Ballerina"]
keywords = ["security", "hash", "hmac", "sign", "encrypt", "decrypt", "private key", "public key"]
repository = "https://github.com/ballerina-platform/module-ballerina-crypto"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.4"

[[platform.java11.dependency]]
path = "../native/build/libs/crypto-native-2.2.2-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/bcpkix-jdk15on-1.69.jar"

[[platform.java11.dependency]]
path = "./lib/bcprov-jdk15on-1.69.jar"
