[package]
org = "ballerina"
name = "crypto"
version = "2.6.2"
authors = ["Ballerina"]
keywords = ["security", "hash", "hmac", "sign", "encrypt", "decrypt", "private key", "public key"]
repository = "https://github.com/ballerina-platform/module-ballerina-crypto"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "crypto-native"
version = "2.6.2"
path = "../native/build/libs/crypto-native-2.6.2.jar"

[[platform.java17.dependency]]
groupId = "org.bouncycastle"
artifactId = "bcpkix-jdk18on"
version = "1.77"
path = "./lib/bcpkix-jdk18on-1.77.jar"

[[platform.java17.dependency]]
groupId = "org.bouncycastle"
artifactId = "bcprov-jdk18on"
version = "1.77"
path = "./lib/bcprov-jdk18on-1.77.jar"
