[package]
org = "ballerina"
name = "crypto"
version = "2.3.1"
authors = ["Ballerina"]
keywords = ["security", "hash", "hmac", "sign", "encrypt", "decrypt", "private key", "public key"]
repository = "https://github.com/ballerina-platform/module-ballerina-crypto"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.3.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "crypto-native"
version = "2.3.1"
path = "../native/build/libs/crypto-native-2.3.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/bcpkix-fips-1.0.3.jar"

# [[platform.java11.dependency]]
# path = "./lib/bcprov-jdk15on-@bouncycastle.version@.jar"

[[platform.java11.dependency]]
path = "./lib/bc-fips-1.0.2.3.jar"
