[package]
org = "ballerina"
name = "crypto"
version = "2.4.1"
authors = ["Ballerina"]
keywords = ["security", "hash", "hmac", "sign", "encrypt", "decrypt", "private key", "public key"]
repository = "https://github.com/ballerina-platform/module-ballerina-crypto"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "crypto-native"
version = "2.4.1"
path = "../native/build/libs/crypto-native-2.4.1.jar"

[[platform.java11.dependency]]
groupId = "org.bouncycastle"
artifactId = "bcpkix-jdk18on"
version = "1.74"
path = "./lib/bcpkix-jdk18on-1.74.jar"

[[platform.java11.dependency]]
groupId = "org.bouncycastle"
artifactId = "bcprov-jdk18on"
version = "1.74"
path = "./lib/bcprov-jdk18on-1.74.jar"
